name: Bug report
description: Report a problem.
title: '[bug] <short title>'
labels: ['bug']
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-check
      options:
        - label: I searched existing issues.
          required: true
        - label: I can reproduce this on the latest version.
          required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, minimal reproducible case.
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Versions
      description: 'App/System version, Foundry VTT version, Browser/OS.'
      placeholder: 'System 0.8.1, Foundry v12.331, Chrome 124, Windows 11'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Console/Server logs (attach as text).
      render: bash
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Optional
